using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Hezium.Memory;

public sealed partial class BigArray<T>
{
    private static Func<int, Array> CreateFactory1To64(int chunkSize)
    {
        return chunkSize switch
        {
            1 => chunks => new ElementChunk1[chunks],
            2 => chunks => new ElementChunk2[chunks],
            3 => chunks => new ElementChunk3[chunks],
            4 => chunks => new ElementChunk4[chunks],
            5 => chunks => new ElementChunk5[chunks],
            6 => chunks => new ElementChunk6[chunks],
            7 => chunks => new ElementChunk7[chunks],
            8 => chunks => new ElementChunk8[chunks],
            9 => chunks => new ElementChunk9[chunks],
            10 => chunks => new ElementChunk10[chunks],
            11 => chunks => new ElementChunk11[chunks],
            12 => chunks => new ElementChunk12[chunks],
            13 => chunks => new ElementChunk13[chunks],
            14 => chunks => new ElementChunk14[chunks],
            15 => chunks => new ElementChunk15[chunks],
            16 => chunks => new ElementChunk16[chunks],
            17 => chunks => new ElementChunk17[chunks],
            18 => chunks => new ElementChunk18[chunks],
            19 => chunks => new ElementChunk19[chunks],
            20 => chunks => new ElementChunk20[chunks],
            21 => chunks => new ElementChunk21[chunks],
            22 => chunks => new ElementChunk22[chunks],
            23 => chunks => new ElementChunk23[chunks],
            24 => chunks => new ElementChunk24[chunks],
            25 => chunks => new ElementChunk25[chunks],
            26 => chunks => new ElementChunk26[chunks],
            27 => chunks => new ElementChunk27[chunks],
            28 => chunks => new ElementChunk28[chunks],
            29 => chunks => new ElementChunk29[chunks],
            30 => chunks => new ElementChunk30[chunks],
            31 => chunks => new ElementChunk31[chunks],
            32 => chunks => new ElementChunk32[chunks],
            33 => chunks => new ElementChunk33[chunks],
            34 => chunks => new ElementChunk34[chunks],
            35 => chunks => new ElementChunk35[chunks],
            36 => chunks => new ElementChunk36[chunks],
            37 => chunks => new ElementChunk37[chunks],
            38 => chunks => new ElementChunk38[chunks],
            39 => chunks => new ElementChunk39[chunks],
            40 => chunks => new ElementChunk40[chunks],
            41 => chunks => new ElementChunk41[chunks],
            42 => chunks => new ElementChunk42[chunks],
            43 => chunks => new ElementChunk43[chunks],
            44 => chunks => new ElementChunk44[chunks],
            45 => chunks => new ElementChunk45[chunks],
            46 => chunks => new ElementChunk46[chunks],
            47 => chunks => new ElementChunk47[chunks],
            48 => chunks => new ElementChunk48[chunks],
            49 => chunks => new ElementChunk49[chunks],
            50 => chunks => new ElementChunk50[chunks],
            51 => chunks => new ElementChunk51[chunks],
            52 => chunks => new ElementChunk52[chunks],
            53 => chunks => new ElementChunk53[chunks],
            54 => chunks => new ElementChunk54[chunks],
            55 => chunks => new ElementChunk55[chunks],
            56 => chunks => new ElementChunk56[chunks],
            57 => chunks => new ElementChunk57[chunks],
            58 => chunks => new ElementChunk58[chunks],
            59 => chunks => new ElementChunk59[chunks],
            60 => chunks => new ElementChunk60[chunks],
            61 => chunks => new ElementChunk61[chunks],
            62 => chunks => new ElementChunk62[chunks],
            63 => chunks => new ElementChunk63[chunks],
            64 => chunks => new ElementChunk64[chunks],
            _ => throw new UnreachableException()
        };
    }

    private static Func<int, Array> CreateFactory65To128(int chunkSize)
    {
        return chunkSize switch
        {
            65 => chunks => new ElementChunk65[chunks],
            66 => chunks => new ElementChunk66[chunks],
            67 => chunks => new ElementChunk67[chunks],
            68 => chunks => new ElementChunk68[chunks],
            69 => chunks => new ElementChunk69[chunks],
            70 => chunks => new ElementChunk70[chunks],
            71 => chunks => new ElementChunk71[chunks],
            72 => chunks => new ElementChunk72[chunks],
            73 => chunks => new ElementChunk73[chunks],
            74 => chunks => new ElementChunk74[chunks],
            75 => chunks => new ElementChunk75[chunks],
            76 => chunks => new ElementChunk76[chunks],
            77 => chunks => new ElementChunk77[chunks],
            78 => chunks => new ElementChunk78[chunks],
            79 => chunks => new ElementChunk79[chunks],
            80 => chunks => new ElementChunk80[chunks],
            81 => chunks => new ElementChunk81[chunks],
            82 => chunks => new ElementChunk82[chunks],
            83 => chunks => new ElementChunk83[chunks],
            84 => chunks => new ElementChunk84[chunks],
            85 => chunks => new ElementChunk85[chunks],
            86 => chunks => new ElementChunk86[chunks],
            87 => chunks => new ElementChunk87[chunks],
            88 => chunks => new ElementChunk88[chunks],
            89 => chunks => new ElementChunk89[chunks],
            90 => chunks => new ElementChunk90[chunks],
            91 => chunks => new ElementChunk91[chunks],
            92 => chunks => new ElementChunk92[chunks],
            93 => chunks => new ElementChunk93[chunks],
            94 => chunks => new ElementChunk94[chunks],
            95 => chunks => new ElementChunk95[chunks],
            96 => chunks => new ElementChunk96[chunks],
            97 => chunks => new ElementChunk97[chunks],
            98 => chunks => new ElementChunk98[chunks],
            99 => chunks => new ElementChunk99[chunks],
            100 => chunks => new ElementChunk100[chunks],
            101 => chunks => new ElementChunk101[chunks],
            102 => chunks => new ElementChunk102[chunks],
            103 => chunks => new ElementChunk103[chunks],
            104 => chunks => new ElementChunk104[chunks],
            105 => chunks => new ElementChunk105[chunks],
            106 => chunks => new ElementChunk106[chunks],
            107 => chunks => new ElementChunk107[chunks],
            108 => chunks => new ElementChunk108[chunks],
            109 => chunks => new ElementChunk109[chunks],
            110 => chunks => new ElementChunk110[chunks],
            111 => chunks => new ElementChunk111[chunks],
            112 => chunks => new ElementChunk112[chunks],
            113 => chunks => new ElementChunk113[chunks],
            114 => chunks => new ElementChunk114[chunks],
            115 => chunks => new ElementChunk115[chunks],
            116 => chunks => new ElementChunk116[chunks],
            117 => chunks => new ElementChunk117[chunks],
            118 => chunks => new ElementChunk118[chunks],
            119 => chunks => new ElementChunk119[chunks],
            120 => chunks => new ElementChunk120[chunks],
            121 => chunks => new ElementChunk121[chunks],
            122 => chunks => new ElementChunk122[chunks],
            123 => chunks => new ElementChunk123[chunks],
            124 => chunks => new ElementChunk124[chunks],
            125 => chunks => new ElementChunk125[chunks],
            126 => chunks => new ElementChunk126[chunks],
            127 => chunks => new ElementChunk127[chunks],
            128 => chunks => new ElementChunk128[chunks],
            _ => throw new UnreachableException()
        };
    }

    private static Func<int, Array> CreateFactory129To192(int chunkSize)
    {
        return chunkSize switch
        {
            129 => chunks => new ElementChunk129[chunks],
            130 => chunks => new ElementChunk130[chunks],
            131 => chunks => new ElementChunk131[chunks],
            132 => chunks => new ElementChunk132[chunks],
            133 => chunks => new ElementChunk133[chunks],
            134 => chunks => new ElementChunk134[chunks],
            135 => chunks => new ElementChunk135[chunks],
            136 => chunks => new ElementChunk136[chunks],
            137 => chunks => new ElementChunk137[chunks],
            138 => chunks => new ElementChunk138[chunks],
            139 => chunks => new ElementChunk139[chunks],
            140 => chunks => new ElementChunk140[chunks],
            141 => chunks => new ElementChunk141[chunks],
            142 => chunks => new ElementChunk142[chunks],
            143 => chunks => new ElementChunk143[chunks],
            144 => chunks => new ElementChunk144[chunks],
            145 => chunks => new ElementChunk145[chunks],
            146 => chunks => new ElementChunk146[chunks],
            147 => chunks => new ElementChunk147[chunks],
            148 => chunks => new ElementChunk148[chunks],
            149 => chunks => new ElementChunk149[chunks],
            150 => chunks => new ElementChunk150[chunks],
            151 => chunks => new ElementChunk151[chunks],
            152 => chunks => new ElementChunk152[chunks],
            153 => chunks => new ElementChunk153[chunks],
            154 => chunks => new ElementChunk154[chunks],
            155 => chunks => new ElementChunk155[chunks],
            156 => chunks => new ElementChunk156[chunks],
            157 => chunks => new ElementChunk157[chunks],
            158 => chunks => new ElementChunk158[chunks],
            159 => chunks => new ElementChunk159[chunks],
            160 => chunks => new ElementChunk160[chunks],
            161 => chunks => new ElementChunk161[chunks],
            162 => chunks => new ElementChunk162[chunks],
            163 => chunks => new ElementChunk163[chunks],
            164 => chunks => new ElementChunk164[chunks],
            165 => chunks => new ElementChunk165[chunks],
            166 => chunks => new ElementChunk166[chunks],
            167 => chunks => new ElementChunk167[chunks],
            168 => chunks => new ElementChunk168[chunks],
            169 => chunks => new ElementChunk169[chunks],
            170 => chunks => new ElementChunk170[chunks],
            171 => chunks => new ElementChunk171[chunks],
            172 => chunks => new ElementChunk172[chunks],
            173 => chunks => new ElementChunk173[chunks],
            174 => chunks => new ElementChunk174[chunks],
            175 => chunks => new ElementChunk175[chunks],
            176 => chunks => new ElementChunk176[chunks],
            177 => chunks => new ElementChunk177[chunks],
            178 => chunks => new ElementChunk178[chunks],
            179 => chunks => new ElementChunk179[chunks],
            180 => chunks => new ElementChunk180[chunks],
            181 => chunks => new ElementChunk181[chunks],
            182 => chunks => new ElementChunk182[chunks],
            183 => chunks => new ElementChunk183[chunks],
            184 => chunks => new ElementChunk184[chunks],
            185 => chunks => new ElementChunk185[chunks],
            186 => chunks => new ElementChunk186[chunks],
            187 => chunks => new ElementChunk187[chunks],
            188 => chunks => new ElementChunk188[chunks],
            189 => chunks => new ElementChunk189[chunks],
            190 => chunks => new ElementChunk190[chunks],
            191 => chunks => new ElementChunk191[chunks],
            192 => chunks => new ElementChunk192[chunks],
            _ => throw new UnreachableException()
        };
    }

    private static Func<int, Array> CreateFactory193To255(int chunkSize)
    {
        return chunkSize switch
        {
            193 => chunks => new ElementChunk193[chunks],
            194 => chunks => new ElementChunk194[chunks],
            195 => chunks => new ElementChunk195[chunks],
            196 => chunks => new ElementChunk196[chunks],
            197 => chunks => new ElementChunk197[chunks],
            198 => chunks => new ElementChunk198[chunks],
            199 => chunks => new ElementChunk199[chunks],
            200 => chunks => new ElementChunk200[chunks],
            201 => chunks => new ElementChunk201[chunks],
            202 => chunks => new ElementChunk202[chunks],
            203 => chunks => new ElementChunk203[chunks],
            204 => chunks => new ElementChunk204[chunks],
            205 => chunks => new ElementChunk205[chunks],
            206 => chunks => new ElementChunk206[chunks],
            207 => chunks => new ElementChunk207[chunks],
            208 => chunks => new ElementChunk208[chunks],
            209 => chunks => new ElementChunk209[chunks],
            210 => chunks => new ElementChunk210[chunks],
            211 => chunks => new ElementChunk211[chunks],
            212 => chunks => new ElementChunk212[chunks],
            213 => chunks => new ElementChunk213[chunks],
            214 => chunks => new ElementChunk214[chunks],
            215 => chunks => new ElementChunk215[chunks],
            216 => chunks => new ElementChunk216[chunks],
            217 => chunks => new ElementChunk217[chunks],
            218 => chunks => new ElementChunk218[chunks],
            219 => chunks => new ElementChunk219[chunks],
            220 => chunks => new ElementChunk220[chunks],
            221 => chunks => new ElementChunk221[chunks],
            222 => chunks => new ElementChunk222[chunks],
            223 => chunks => new ElementChunk223[chunks],
            224 => chunks => new ElementChunk224[chunks],
            225 => chunks => new ElementChunk225[chunks],
            226 => chunks => new ElementChunk226[chunks],
            227 => chunks => new ElementChunk227[chunks],
            228 => chunks => new ElementChunk228[chunks],
            229 => chunks => new ElementChunk229[chunks],
            230 => chunks => new ElementChunk230[chunks],
            231 => chunks => new ElementChunk231[chunks],
            232 => chunks => new ElementChunk232[chunks],
            233 => chunks => new ElementChunk233[chunks],
            234 => chunks => new ElementChunk234[chunks],
            235 => chunks => new ElementChunk235[chunks],
            236 => chunks => new ElementChunk236[chunks],
            237 => chunks => new ElementChunk237[chunks],
            238 => chunks => new ElementChunk238[chunks],
            239 => chunks => new ElementChunk239[chunks],
            240 => chunks => new ElementChunk240[chunks],
            241 => chunks => new ElementChunk241[chunks],
            242 => chunks => new ElementChunk242[chunks],
            243 => chunks => new ElementChunk243[chunks],
            244 => chunks => new ElementChunk244[chunks],
            245 => chunks => new ElementChunk245[chunks],
            246 => chunks => new ElementChunk246[chunks],
            247 => chunks => new ElementChunk247[chunks],
            248 => chunks => new ElementChunk248[chunks],
            249 => chunks => new ElementChunk249[chunks],
            250 => chunks => new ElementChunk250[chunks],
            251 => chunks => new ElementChunk251[chunks],
            252 => chunks => new ElementChunk252[chunks],
            253 => chunks => new ElementChunk253[chunks],
            254 => chunks => new ElementChunk254[chunks],
            255 => chunks => new ElementChunk255[chunks],
            _ => throw new UnreachableException()
        };
    }

    private static Func<int, Array> CreateFactory257To512(int chunkSize)
    {
        return chunkSize switch
        {
            257 => chunks => new ElementChunk257[chunks],
            258 => chunks => new ElementChunk258[chunks],
            259 => chunks => new ElementChunk259[chunks],
            260 => chunks => new ElementChunk260[chunks],
            261 => chunks => new ElementChunk261[chunks],
            262 => chunks => new ElementChunk262[chunks],
            263 => chunks => new ElementChunk263[chunks],
            264 => chunks => new ElementChunk264[chunks],
            265 => chunks => new ElementChunk265[chunks],
            266 => chunks => new ElementChunk266[chunks],
            267 => chunks => new ElementChunk267[chunks],
            268 => chunks => new ElementChunk268[chunks],
            269 => chunks => new ElementChunk269[chunks],
            270 => chunks => new ElementChunk270[chunks],
            271 => chunks => new ElementChunk271[chunks],
            273 => chunks => new ElementChunk273[chunks],
            274 => chunks => new ElementChunk274[chunks],
            275 => chunks => new ElementChunk275[chunks],
            276 => chunks => new ElementChunk276[chunks],
            277 => chunks => new ElementChunk277[chunks],
            278 => chunks => new ElementChunk278[chunks],
            280 => chunks => new ElementChunk280[chunks],
            281 => chunks => new ElementChunk281[chunks],
            282 => chunks => new ElementChunk282[chunks],
            283 => chunks => new ElementChunk283[chunks],
            284 => chunks => new ElementChunk284[chunks],
            286 => chunks => new ElementChunk286[chunks],
            287 => chunks => new ElementChunk287[chunks],
            288 => chunks => new ElementChunk288[chunks],
            289 => chunks => new ElementChunk289[chunks],
            291 => chunks => new ElementChunk291[chunks],
            292 => chunks => new ElementChunk292[chunks],
            293 => chunks => new ElementChunk293[chunks],
            295 => chunks => new ElementChunk295[chunks],
            296 => chunks => new ElementChunk296[chunks],
            297 => chunks => new ElementChunk297[chunks],
            299 => chunks => new ElementChunk299[chunks],
            300 => chunks => new ElementChunk300[chunks],
            302 => chunks => new ElementChunk302[chunks],
            303 => chunks => new ElementChunk303[chunks],
            304 => chunks => new ElementChunk304[chunks],
            306 => chunks => new ElementChunk306[chunks],
            307 => chunks => new ElementChunk307[chunks],
            309 => chunks => new ElementChunk309[chunks],
            310 => chunks => new ElementChunk310[chunks],
            312 => chunks => new ElementChunk312[chunks],
            313 => chunks => new ElementChunk313[chunks],
            315 => chunks => new ElementChunk315[chunks],
            316 => chunks => new ElementChunk316[chunks],
            318 => chunks => new ElementChunk318[chunks],
            319 => chunks => new ElementChunk319[chunks],
            321 => chunks => new ElementChunk321[chunks],
            322 => chunks => new ElementChunk322[chunks],
            324 => chunks => new ElementChunk324[chunks],
            326 => chunks => new ElementChunk326[chunks],
            327 => chunks => new ElementChunk327[chunks],
            329 => chunks => new ElementChunk329[chunks],
            330 => chunks => new ElementChunk330[chunks],
            332 => chunks => new ElementChunk332[chunks],
            334 => chunks => new ElementChunk334[chunks],
            336 => chunks => new ElementChunk336[chunks],
            337 => chunks => new ElementChunk337[chunks],
            339 => chunks => new ElementChunk339[chunks],
            341 => chunks => new ElementChunk341[chunks],
            343 => chunks => new ElementChunk343[chunks],
            344 => chunks => new ElementChunk344[chunks],
            346 => chunks => new ElementChunk346[chunks],
            348 => chunks => new ElementChunk348[chunks],
            350 => chunks => new ElementChunk350[chunks],
            352 => chunks => new ElementChunk352[chunks],
            354 => chunks => new ElementChunk354[chunks],
            356 => chunks => new ElementChunk356[chunks],
            358 => chunks => new ElementChunk358[chunks],
            360 => chunks => new ElementChunk360[chunks],
            362 => chunks => new ElementChunk362[chunks],
            364 => chunks => new ElementChunk364[chunks],
            366 => chunks => new ElementChunk366[chunks],
            368 => chunks => new ElementChunk368[chunks],
            370 => chunks => new ElementChunk370[chunks],
            372 => chunks => new ElementChunk372[chunks],
            374 => chunks => new ElementChunk374[chunks],
            376 => chunks => new ElementChunk376[chunks],
            378 => chunks => new ElementChunk378[chunks],
            381 => chunks => new ElementChunk381[chunks],
            383 => chunks => new ElementChunk383[chunks],
            385 => chunks => new ElementChunk385[chunks],
            387 => chunks => new ElementChunk387[chunks],
            390 => chunks => new ElementChunk390[chunks],
            392 => chunks => new ElementChunk392[chunks],
            394 => chunks => new ElementChunk394[chunks],
            397 => chunks => new ElementChunk397[chunks],
            399 => chunks => new ElementChunk399[chunks],
            402 => chunks => new ElementChunk402[chunks],
            404 => chunks => new ElementChunk404[chunks],
            407 => chunks => new ElementChunk407[chunks],
            409 => chunks => new ElementChunk409[chunks],
            412 => chunks => new ElementChunk412[chunks],
            414 => chunks => new ElementChunk414[chunks],
            417 => chunks => new ElementChunk417[chunks],
            420 => chunks => new ElementChunk420[chunks],
            422 => chunks => new ElementChunk422[chunks],
            425 => chunks => new ElementChunk425[chunks],
            428 => chunks => new ElementChunk428[chunks],
            431 => chunks => new ElementChunk431[chunks],
            434 => chunks => new ElementChunk434[chunks],
            436 => chunks => new ElementChunk436[chunks],
            439 => chunks => new ElementChunk439[chunks],
            442 => chunks => new ElementChunk442[chunks],
            445 => chunks => new ElementChunk445[chunks],
            448 => chunks => new ElementChunk448[chunks],
            451 => chunks => new ElementChunk451[chunks],
            455 => chunks => new ElementChunk455[chunks],
            458 => chunks => new ElementChunk458[chunks],
            461 => chunks => new ElementChunk461[chunks],
            464 => chunks => new ElementChunk464[chunks],
            468 => chunks => new ElementChunk468[chunks],
            471 => chunks => new ElementChunk471[chunks],
            474 => chunks => new ElementChunk474[chunks],
            478 => chunks => new ElementChunk478[chunks],
            481 => chunks => new ElementChunk481[chunks],
            485 => chunks => new ElementChunk485[chunks],
            489 => chunks => new ElementChunk489[chunks],
            492 => chunks => new ElementChunk492[chunks],
            496 => chunks => new ElementChunk496[chunks],
            500 => chunks => new ElementChunk500[chunks],
            504 => chunks => new ElementChunk504[chunks],
            508 => chunks => new ElementChunk508[chunks],
            511 => chunks => new ElementChunk511[chunks],
            _ => throw new UnreachableException()
        };
    }

    private static Func<int, Array> CreateFactory516To1023(int chunkSize)
    {
        return chunkSize switch
        {
            516 => chunks => new ElementChunk516[chunks],
            520 => chunks => new ElementChunk520[chunks],
            524 => chunks => new ElementChunk524[chunks],
            528 => chunks => new ElementChunk528[chunks],
            532 => chunks => new ElementChunk532[chunks],
            537 => chunks => new ElementChunk537[chunks],
            541 => chunks => new ElementChunk541[chunks],
            546 => chunks => new ElementChunk546[chunks],
            550 => chunks => new ElementChunk550[chunks],
            555 => chunks => new ElementChunk555[chunks],
            560 => chunks => new ElementChunk560[chunks],
            564 => chunks => new ElementChunk564[chunks],
            569 => chunks => new ElementChunk569[chunks],
            574 => chunks => new ElementChunk574[chunks],
            579 => chunks => new ElementChunk579[chunks],
            585 => chunks => new ElementChunk585[chunks],
            590 => chunks => new ElementChunk590[chunks],
            595 => chunks => new ElementChunk595[chunks],
            601 => chunks => new ElementChunk601[chunks],
            606 => chunks => new ElementChunk606[chunks],
            612 => chunks => new ElementChunk612[chunks],
            618 => chunks => new ElementChunk618[chunks],
            624 => chunks => new ElementChunk624[chunks],
            630 => chunks => new ElementChunk630[chunks],
            636 => chunks => new ElementChunk636[chunks],
            642 => chunks => new ElementChunk642[chunks],
            648 => chunks => new ElementChunk648[chunks],
            655 => chunks => new ElementChunk655[chunks],
            661 => chunks => new ElementChunk661[chunks],
            668 => chunks => new ElementChunk668[chunks],
            675 => chunks => new ElementChunk675[chunks],
            682 => chunks => new ElementChunk682[chunks],
            689 => chunks => new ElementChunk689[chunks],
            697 => chunks => new ElementChunk697[chunks],
            704 => chunks => new ElementChunk704[chunks],
            712 => chunks => new ElementChunk712[chunks],
            720 => chunks => new ElementChunk720[chunks],
            728 => chunks => new ElementChunk728[chunks],
            736 => chunks => new ElementChunk736[chunks],
            744 => chunks => new ElementChunk744[chunks],
            753 => chunks => new ElementChunk753[chunks],
            762 => chunks => new ElementChunk762[chunks],
            771 => chunks => new ElementChunk771[chunks],
            780 => chunks => new ElementChunk780[chunks],
            789 => chunks => new ElementChunk789[chunks],
            799 => chunks => new ElementChunk799[chunks],
            809 => chunks => new ElementChunk809[chunks],
            819 => chunks => new ElementChunk819[chunks],
            829 => chunks => new ElementChunk829[chunks],
            840 => chunks => new ElementChunk840[chunks],
            851 => chunks => new ElementChunk851[chunks],
            862 => chunks => new ElementChunk862[chunks],
            873 => chunks => new ElementChunk873[chunks],
            885 => chunks => new ElementChunk885[chunks],
            897 => chunks => new ElementChunk897[chunks],
            910 => chunks => new ElementChunk910[chunks],
            923 => chunks => new ElementChunk923[chunks],
            936 => chunks => new ElementChunk936[chunks],
            949 => chunks => new ElementChunk949[chunks],
            963 => chunks => new ElementChunk963[chunks],
            978 => chunks => new ElementChunk978[chunks],
            992 => chunks => new ElementChunk992[chunks],
            1008 => chunks => new ElementChunk1008[chunks],
            1023 => chunks => new ElementChunk1023[chunks],
            _ => throw new UnreachableException()
        };
    }

    private static Func<int, Array> CreateFactory1024To65535(int chunkSize)
    {
        return chunkSize switch
        {
            1040 => chunks => new ElementChunk1040[chunks],
            1057 => chunks => new ElementChunk1057[chunks],
            1074 => chunks => new ElementChunk1074[chunks],
            1092 => chunks => new ElementChunk1092[chunks],
            1110 => chunks => new ElementChunk1110[chunks],
            1129 => chunks => new ElementChunk1129[chunks],
            1149 => chunks => new ElementChunk1149[chunks],
            1170 => chunks => new ElementChunk1170[chunks],
            1191 => chunks => new ElementChunk1191[chunks],
            1213 => chunks => new ElementChunk1213[chunks],
            1236 => chunks => new ElementChunk1236[chunks],
            1260 => chunks => new ElementChunk1260[chunks],
            1285 => chunks => new ElementChunk1285[chunks],
            1310 => chunks => new ElementChunk1310[chunks],
            1337 => chunks => new ElementChunk1337[chunks],
            1365 => chunks => new ElementChunk1365[chunks],
            1394 => chunks => new ElementChunk1394[chunks],
            1424 => chunks => new ElementChunk1424[chunks],
            1456 => chunks => new ElementChunk1456[chunks],
            1489 => chunks => new ElementChunk1489[chunks],
            1524 => chunks => new ElementChunk1524[chunks],
            1560 => chunks => new ElementChunk1560[chunks],
            1598 => chunks => new ElementChunk1598[chunks],
            1638 => chunks => new ElementChunk1638[chunks],
            1680 => chunks => new ElementChunk1680[chunks],
            1724 => chunks => new ElementChunk1724[chunks],
            1771 => chunks => new ElementChunk1771[chunks],
            1820 => chunks => new ElementChunk1820[chunks],
            1872 => chunks => new ElementChunk1872[chunks],
            1927 => chunks => new ElementChunk1927[chunks],
            1985 => chunks => new ElementChunk1985[chunks],
            2047 => chunks => new ElementChunk2047[chunks],
            2114 => chunks => new ElementChunk2114[chunks],
            2184 => chunks => new ElementChunk2184[chunks],
            2259 => chunks => new ElementChunk2259[chunks],
            2340 => chunks => new ElementChunk2340[chunks],
            2427 => chunks => new ElementChunk2427[chunks],
            2520 => chunks => new ElementChunk2520[chunks],
            2621 => chunks => new ElementChunk2621[chunks],
            2730 => chunks => new ElementChunk2730[chunks],
            2849 => chunks => new ElementChunk2849[chunks],
            2978 => chunks => new ElementChunk2978[chunks],
            3120 => chunks => new ElementChunk3120[chunks],
            3276 => chunks => new ElementChunk3276[chunks],
            3449 => chunks => new ElementChunk3449[chunks],
            3640 => chunks => new ElementChunk3640[chunks],
            3855 => chunks => new ElementChunk3855[chunks],
            4095 => chunks => new ElementChunk4095[chunks],
            4369 => chunks => new ElementChunk4369[chunks],
            4681 => chunks => new ElementChunk4681[chunks],
            5041 => chunks => new ElementChunk5041[chunks],
            5461 => chunks => new ElementChunk5461[chunks],
            5957 => chunks => new ElementChunk5957[chunks],
            6553 => chunks => new ElementChunk6553[chunks],
            7281 => chunks => new ElementChunk7281[chunks],
            8191 => chunks => new ElementChunk8191[chunks],
            9362 => chunks => new ElementChunk9362[chunks],
            10922 => chunks => new ElementChunk10922[chunks],
            13107 => chunks => new ElementChunk13107[chunks],
            16383 => chunks => new ElementChunk16383[chunks],
            21845 => chunks => new ElementChunk21845[chunks],
            32767 => chunks => new ElementChunk32767[chunks],
            65535 => chunks => new ElementChunk65535[chunks],
            _ => throw new UnreachableException()
        };
    }

    private static Func<int, Array> CreateBigArrayFactory(int chunkSize) => chunkSize switch
    {
        <= 64 => CreateFactory1To64(chunkSize),
        <= 128 => CreateFactory65To128(chunkSize),
        <= 192 => CreateFactory129To192(chunkSize),
        <= 255 => CreateFactory193To255(chunkSize),
        <= 512 => CreateFactory257To512(chunkSize),
        <= 1023 => CreateFactory516To1023(chunkSize),
        <= 65535 => CreateFactory1024To65535(chunkSize),
        _ => throw new UnreachableException()
    };

    private static Array CreateBigArraySlow(nint length)
    {
        var chunkSize = 65535 / Unsafe.SizeOf<T>();
        return CreateBigArrayFactory(chunkSize)((int)((length / chunkSize) + (length % chunkSize == 0 ? 0 : 1)));
    }
}
