using System.Runtime.CompilerServices;

namespace Hezium.Collections;

public sealed partial class BigArray<T>
{
    [InlineArray(1)] struct ElementChunk1 { private T _first; }
    [InlineArray(2)] struct ElementChunk2 { private T _first; }
    [InlineArray(3)] struct ElementChunk3 { private T _first; }
    [InlineArray(4)] struct ElementChunk4 { private T _first; }
    [InlineArray(5)] struct ElementChunk5 { private T _first; }
    [InlineArray(6)] struct ElementChunk6 { private T _first; }
    [InlineArray(7)] struct ElementChunk7 { private T _first; }
    [InlineArray(8)] struct ElementChunk8 { private T _first; }
    [InlineArray(9)] struct ElementChunk9 { private T _first; }
    [InlineArray(10)] struct ElementChunk10 { private T _first; }
    [InlineArray(11)] struct ElementChunk11 { private T _first; }
    [InlineArray(12)] struct ElementChunk12 { private T _first; }
    [InlineArray(13)] struct ElementChunk13 { private T _first; }
    [InlineArray(14)] struct ElementChunk14 { private T _first; }
    [InlineArray(15)] struct ElementChunk15 { private T _first; }
    [InlineArray(16)] struct ElementChunk16 { private T _first; }
    [InlineArray(17)] struct ElementChunk17 { private T _first; }
    [InlineArray(18)] struct ElementChunk18 { private T _first; }
    [InlineArray(19)] struct ElementChunk19 { private T _first; }
    [InlineArray(20)] struct ElementChunk20 { private T _first; }
    [InlineArray(21)] struct ElementChunk21 { private T _first; }
    [InlineArray(22)] struct ElementChunk22 { private T _first; }
    [InlineArray(23)] struct ElementChunk23 { private T _first; }
    [InlineArray(24)] struct ElementChunk24 { private T _first; }
    [InlineArray(25)] struct ElementChunk25 { private T _first; }
    [InlineArray(26)] struct ElementChunk26 { private T _first; }
    [InlineArray(27)] struct ElementChunk27 { private T _first; }
    [InlineArray(28)] struct ElementChunk28 { private T _first; }
    [InlineArray(29)] struct ElementChunk29 { private T _first; }
    [InlineArray(30)] struct ElementChunk30 { private T _first; }
    [InlineArray(31)] struct ElementChunk31 { private T _first; }
    [InlineArray(32)] struct ElementChunk32 { private T _first; }
    [InlineArray(33)] struct ElementChunk33 { private T _first; }
    [InlineArray(34)] struct ElementChunk34 { private T _first; }
    [InlineArray(35)] struct ElementChunk35 { private T _first; }
    [InlineArray(36)] struct ElementChunk36 { private T _first; }
    [InlineArray(37)] struct ElementChunk37 { private T _first; }
    [InlineArray(38)] struct ElementChunk38 { private T _first; }
    [InlineArray(39)] struct ElementChunk39 { private T _first; }
    [InlineArray(40)] struct ElementChunk40 { private T _first; }
    [InlineArray(41)] struct ElementChunk41 { private T _first; }
    [InlineArray(42)] struct ElementChunk42 { private T _first; }
    [InlineArray(43)] struct ElementChunk43 { private T _first; }
    [InlineArray(44)] struct ElementChunk44 { private T _first; }
    [InlineArray(45)] struct ElementChunk45 { private T _first; }
    [InlineArray(46)] struct ElementChunk46 { private T _first; }
    [InlineArray(47)] struct ElementChunk47 { private T _first; }
    [InlineArray(48)] struct ElementChunk48 { private T _first; }
    [InlineArray(49)] struct ElementChunk49 { private T _first; }
    [InlineArray(50)] struct ElementChunk50 { private T _first; }
    [InlineArray(51)] struct ElementChunk51 { private T _first; }
    [InlineArray(52)] struct ElementChunk52 { private T _first; }
    [InlineArray(53)] struct ElementChunk53 { private T _first; }
    [InlineArray(54)] struct ElementChunk54 { private T _first; }
    [InlineArray(55)] struct ElementChunk55 { private T _first; }
    [InlineArray(56)] struct ElementChunk56 { private T _first; }
    [InlineArray(57)] struct ElementChunk57 { private T _first; }
    [InlineArray(58)] struct ElementChunk58 { private T _first; }
    [InlineArray(59)] struct ElementChunk59 { private T _first; }
    [InlineArray(60)] struct ElementChunk60 { private T _first; }
    [InlineArray(61)] struct ElementChunk61 { private T _first; }
    [InlineArray(62)] struct ElementChunk62 { private T _first; }
    [InlineArray(63)] struct ElementChunk63 { private T _first; }
    [InlineArray(64)] struct ElementChunk64 { private T _first; }
    [InlineArray(65)] struct ElementChunk65 { private T _first; }
    [InlineArray(66)] struct ElementChunk66 { private T _first; }
    [InlineArray(67)] struct ElementChunk67 { private T _first; }
    [InlineArray(68)] struct ElementChunk68 { private T _first; }
    [InlineArray(69)] struct ElementChunk69 { private T _first; }
    [InlineArray(70)] struct ElementChunk70 { private T _first; }
    [InlineArray(71)] struct ElementChunk71 { private T _first; }
    [InlineArray(72)] struct ElementChunk72 { private T _first; }
    [InlineArray(73)] struct ElementChunk73 { private T _first; }
    [InlineArray(74)] struct ElementChunk74 { private T _first; }
    [InlineArray(75)] struct ElementChunk75 { private T _first; }
    [InlineArray(76)] struct ElementChunk76 { private T _first; }
    [InlineArray(77)] struct ElementChunk77 { private T _first; }
    [InlineArray(78)] struct ElementChunk78 { private T _first; }
    [InlineArray(79)] struct ElementChunk79 { private T _first; }
    [InlineArray(80)] struct ElementChunk80 { private T _first; }
    [InlineArray(81)] struct ElementChunk81 { private T _first; }
    [InlineArray(82)] struct ElementChunk82 { private T _first; }
    [InlineArray(83)] struct ElementChunk83 { private T _first; }
    [InlineArray(84)] struct ElementChunk84 { private T _first; }
    [InlineArray(85)] struct ElementChunk85 { private T _first; }
    [InlineArray(86)] struct ElementChunk86 { private T _first; }
    [InlineArray(87)] struct ElementChunk87 { private T _first; }
    [InlineArray(88)] struct ElementChunk88 { private T _first; }
    [InlineArray(89)] struct ElementChunk89 { private T _first; }
    [InlineArray(90)] struct ElementChunk90 { private T _first; }
    [InlineArray(91)] struct ElementChunk91 { private T _first; }
    [InlineArray(92)] struct ElementChunk92 { private T _first; }
    [InlineArray(93)] struct ElementChunk93 { private T _first; }
    [InlineArray(94)] struct ElementChunk94 { private T _first; }
    [InlineArray(95)] struct ElementChunk95 { private T _first; }
    [InlineArray(96)] struct ElementChunk96 { private T _first; }
    [InlineArray(97)] struct ElementChunk97 { private T _first; }
    [InlineArray(98)] struct ElementChunk98 { private T _first; }
    [InlineArray(99)] struct ElementChunk99 { private T _first; }
    [InlineArray(100)] struct ElementChunk100 { private T _first; }
    [InlineArray(101)] struct ElementChunk101 { private T _first; }
    [InlineArray(102)] struct ElementChunk102 { private T _first; }
    [InlineArray(103)] struct ElementChunk103 { private T _first; }
    [InlineArray(104)] struct ElementChunk104 { private T _first; }
    [InlineArray(105)] struct ElementChunk105 { private T _first; }
    [InlineArray(106)] struct ElementChunk106 { private T _first; }
    [InlineArray(107)] struct ElementChunk107 { private T _first; }
    [InlineArray(108)] struct ElementChunk108 { private T _first; }
    [InlineArray(109)] struct ElementChunk109 { private T _first; }
    [InlineArray(110)] struct ElementChunk110 { private T _first; }
    [InlineArray(111)] struct ElementChunk111 { private T _first; }
    [InlineArray(112)] struct ElementChunk112 { private T _first; }
    [InlineArray(113)] struct ElementChunk113 { private T _first; }
    [InlineArray(114)] struct ElementChunk114 { private T _first; }
    [InlineArray(115)] struct ElementChunk115 { private T _first; }
    [InlineArray(116)] struct ElementChunk116 { private T _first; }
    [InlineArray(117)] struct ElementChunk117 { private T _first; }
    [InlineArray(118)] struct ElementChunk118 { private T _first; }
    [InlineArray(119)] struct ElementChunk119 { private T _first; }
    [InlineArray(120)] struct ElementChunk120 { private T _first; }
    [InlineArray(121)] struct ElementChunk121 { private T _first; }
    [InlineArray(122)] struct ElementChunk122 { private T _first; }
    [InlineArray(123)] struct ElementChunk123 { private T _first; }
    [InlineArray(124)] struct ElementChunk124 { private T _first; }
    [InlineArray(125)] struct ElementChunk125 { private T _first; }
    [InlineArray(126)] struct ElementChunk126 { private T _first; }
    [InlineArray(127)] struct ElementChunk127 { private T _first; }
    [InlineArray(128)] struct ElementChunk128 { private T _first; }
    [InlineArray(129)] struct ElementChunk129 { private T _first; }
    [InlineArray(130)] struct ElementChunk130 { private T _first; }
    [InlineArray(131)] struct ElementChunk131 { private T _first; }
    [InlineArray(132)] struct ElementChunk132 { private T _first; }
    [InlineArray(133)] struct ElementChunk133 { private T _first; }
    [InlineArray(134)] struct ElementChunk134 { private T _first; }
    [InlineArray(135)] struct ElementChunk135 { private T _first; }
    [InlineArray(136)] struct ElementChunk136 { private T _first; }
    [InlineArray(137)] struct ElementChunk137 { private T _first; }
    [InlineArray(138)] struct ElementChunk138 { private T _first; }
    [InlineArray(139)] struct ElementChunk139 { private T _first; }
    [InlineArray(140)] struct ElementChunk140 { private T _first; }
    [InlineArray(141)] struct ElementChunk141 { private T _first; }
    [InlineArray(142)] struct ElementChunk142 { private T _first; }
    [InlineArray(143)] struct ElementChunk143 { private T _first; }
    [InlineArray(144)] struct ElementChunk144 { private T _first; }
    [InlineArray(145)] struct ElementChunk145 { private T _first; }
    [InlineArray(146)] struct ElementChunk146 { private T _first; }
    [InlineArray(147)] struct ElementChunk147 { private T _first; }
    [InlineArray(148)] struct ElementChunk148 { private T _first; }
    [InlineArray(149)] struct ElementChunk149 { private T _first; }
    [InlineArray(150)] struct ElementChunk150 { private T _first; }
    [InlineArray(151)] struct ElementChunk151 { private T _first; }
    [InlineArray(152)] struct ElementChunk152 { private T _first; }
    [InlineArray(153)] struct ElementChunk153 { private T _first; }
    [InlineArray(154)] struct ElementChunk154 { private T _first; }
    [InlineArray(155)] struct ElementChunk155 { private T _first; }
    [InlineArray(156)] struct ElementChunk156 { private T _first; }
    [InlineArray(157)] struct ElementChunk157 { private T _first; }
    [InlineArray(158)] struct ElementChunk158 { private T _first; }
    [InlineArray(159)] struct ElementChunk159 { private T _first; }
    [InlineArray(160)] struct ElementChunk160 { private T _first; }
    [InlineArray(161)] struct ElementChunk161 { private T _first; }
    [InlineArray(162)] struct ElementChunk162 { private T _first; }
    [InlineArray(163)] struct ElementChunk163 { private T _first; }
    [InlineArray(164)] struct ElementChunk164 { private T _first; }
    [InlineArray(165)] struct ElementChunk165 { private T _first; }
    [InlineArray(166)] struct ElementChunk166 { private T _first; }
    [InlineArray(167)] struct ElementChunk167 { private T _first; }
    [InlineArray(168)] struct ElementChunk168 { private T _first; }
    [InlineArray(169)] struct ElementChunk169 { private T _first; }
    [InlineArray(170)] struct ElementChunk170 { private T _first; }
    [InlineArray(171)] struct ElementChunk171 { private T _first; }
    [InlineArray(172)] struct ElementChunk172 { private T _first; }
    [InlineArray(173)] struct ElementChunk173 { private T _first; }
    [InlineArray(174)] struct ElementChunk174 { private T _first; }
    [InlineArray(175)] struct ElementChunk175 { private T _first; }
    [InlineArray(176)] struct ElementChunk176 { private T _first; }
    [InlineArray(177)] struct ElementChunk177 { private T _first; }
    [InlineArray(178)] struct ElementChunk178 { private T _first; }
    [InlineArray(179)] struct ElementChunk179 { private T _first; }
    [InlineArray(180)] struct ElementChunk180 { private T _first; }
    [InlineArray(181)] struct ElementChunk181 { private T _first; }
    [InlineArray(182)] struct ElementChunk182 { private T _first; }
    [InlineArray(183)] struct ElementChunk183 { private T _first; }
    [InlineArray(184)] struct ElementChunk184 { private T _first; }
    [InlineArray(185)] struct ElementChunk185 { private T _first; }
    [InlineArray(186)] struct ElementChunk186 { private T _first; }
    [InlineArray(187)] struct ElementChunk187 { private T _first; }
    [InlineArray(188)] struct ElementChunk188 { private T _first; }
    [InlineArray(189)] struct ElementChunk189 { private T _first; }
    [InlineArray(190)] struct ElementChunk190 { private T _first; }
    [InlineArray(191)] struct ElementChunk191 { private T _first; }
    [InlineArray(192)] struct ElementChunk192 { private T _first; }
    [InlineArray(193)] struct ElementChunk193 { private T _first; }
    [InlineArray(194)] struct ElementChunk194 { private T _first; }
    [InlineArray(195)] struct ElementChunk195 { private T _first; }
    [InlineArray(196)] struct ElementChunk196 { private T _first; }
    [InlineArray(197)] struct ElementChunk197 { private T _first; }
    [InlineArray(198)] struct ElementChunk198 { private T _first; }
    [InlineArray(199)] struct ElementChunk199 { private T _first; }
    [InlineArray(200)] struct ElementChunk200 { private T _first; }
    [InlineArray(201)] struct ElementChunk201 { private T _first; }
    [InlineArray(202)] struct ElementChunk202 { private T _first; }
    [InlineArray(203)] struct ElementChunk203 { private T _first; }
    [InlineArray(204)] struct ElementChunk204 { private T _first; }
    [InlineArray(205)] struct ElementChunk205 { private T _first; }
    [InlineArray(206)] struct ElementChunk206 { private T _first; }
    [InlineArray(207)] struct ElementChunk207 { private T _first; }
    [InlineArray(208)] struct ElementChunk208 { private T _first; }
    [InlineArray(209)] struct ElementChunk209 { private T _first; }
    [InlineArray(210)] struct ElementChunk210 { private T _first; }
    [InlineArray(211)] struct ElementChunk211 { private T _first; }
    [InlineArray(212)] struct ElementChunk212 { private T _first; }
    [InlineArray(213)] struct ElementChunk213 { private T _first; }
    [InlineArray(214)] struct ElementChunk214 { private T _first; }
    [InlineArray(215)] struct ElementChunk215 { private T _first; }
    [InlineArray(216)] struct ElementChunk216 { private T _first; }
    [InlineArray(217)] struct ElementChunk217 { private T _first; }
    [InlineArray(218)] struct ElementChunk218 { private T _first; }
    [InlineArray(219)] struct ElementChunk219 { private T _first; }
    [InlineArray(220)] struct ElementChunk220 { private T _first; }
    [InlineArray(221)] struct ElementChunk221 { private T _first; }
    [InlineArray(222)] struct ElementChunk222 { private T _first; }
    [InlineArray(223)] struct ElementChunk223 { private T _first; }
    [InlineArray(224)] struct ElementChunk224 { private T _first; }
    [InlineArray(225)] struct ElementChunk225 { private T _first; }
    [InlineArray(226)] struct ElementChunk226 { private T _first; }
    [InlineArray(227)] struct ElementChunk227 { private T _first; }
    [InlineArray(228)] struct ElementChunk228 { private T _first; }
    [InlineArray(229)] struct ElementChunk229 { private T _first; }
    [InlineArray(230)] struct ElementChunk230 { private T _first; }
    [InlineArray(231)] struct ElementChunk231 { private T _first; }
    [InlineArray(232)] struct ElementChunk232 { private T _first; }
    [InlineArray(233)] struct ElementChunk233 { private T _first; }
    [InlineArray(234)] struct ElementChunk234 { private T _first; }
    [InlineArray(235)] struct ElementChunk235 { private T _first; }
    [InlineArray(236)] struct ElementChunk236 { private T _first; }
    [InlineArray(237)] struct ElementChunk237 { private T _first; }
    [InlineArray(238)] struct ElementChunk238 { private T _first; }
    [InlineArray(239)] struct ElementChunk239 { private T _first; }
    [InlineArray(240)] struct ElementChunk240 { private T _first; }
    [InlineArray(241)] struct ElementChunk241 { private T _first; }
    [InlineArray(242)] struct ElementChunk242 { private T _first; }
    [InlineArray(243)] struct ElementChunk243 { private T _first; }
    [InlineArray(244)] struct ElementChunk244 { private T _first; }
    [InlineArray(245)] struct ElementChunk245 { private T _first; }
    [InlineArray(246)] struct ElementChunk246 { private T _first; }
    [InlineArray(247)] struct ElementChunk247 { private T _first; }
    [InlineArray(248)] struct ElementChunk248 { private T _first; }
    [InlineArray(249)] struct ElementChunk249 { private T _first; }
    [InlineArray(250)] struct ElementChunk250 { private T _first; }
    [InlineArray(251)] struct ElementChunk251 { private T _first; }
    [InlineArray(252)] struct ElementChunk252 { private T _first; }
    [InlineArray(253)] struct ElementChunk253 { private T _first; }
    [InlineArray(254)] struct ElementChunk254 { private T _first; }
    [InlineArray(255)] struct ElementChunk255 { private T _first; }
    [InlineArray(257)] struct ElementChunk257 { private T _first; }
    [InlineArray(258)] struct ElementChunk258 { private T _first; }
    [InlineArray(259)] struct ElementChunk259 { private T _first; }
    [InlineArray(260)] struct ElementChunk260 { private T _first; }
    [InlineArray(261)] struct ElementChunk261 { private T _first; }
    [InlineArray(262)] struct ElementChunk262 { private T _first; }
    [InlineArray(263)] struct ElementChunk263 { private T _first; }
    [InlineArray(264)] struct ElementChunk264 { private T _first; }
    [InlineArray(265)] struct ElementChunk265 { private T _first; }
    [InlineArray(266)] struct ElementChunk266 { private T _first; }
    [InlineArray(267)] struct ElementChunk267 { private T _first; }
    [InlineArray(268)] struct ElementChunk268 { private T _first; }
    [InlineArray(269)] struct ElementChunk269 { private T _first; }
    [InlineArray(270)] struct ElementChunk270 { private T _first; }
    [InlineArray(271)] struct ElementChunk271 { private T _first; }
    [InlineArray(273)] struct ElementChunk273 { private T _first; }
    [InlineArray(274)] struct ElementChunk274 { private T _first; }
    [InlineArray(275)] struct ElementChunk275 { private T _first; }
    [InlineArray(276)] struct ElementChunk276 { private T _first; }
    [InlineArray(277)] struct ElementChunk277 { private T _first; }
    [InlineArray(278)] struct ElementChunk278 { private T _first; }
    [InlineArray(280)] struct ElementChunk280 { private T _first; }
    [InlineArray(281)] struct ElementChunk281 { private T _first; }
    [InlineArray(282)] struct ElementChunk282 { private T _first; }
    [InlineArray(283)] struct ElementChunk283 { private T _first; }
    [InlineArray(284)] struct ElementChunk284 { private T _first; }
    [InlineArray(286)] struct ElementChunk286 { private T _first; }
    [InlineArray(287)] struct ElementChunk287 { private T _first; }
    [InlineArray(288)] struct ElementChunk288 { private T _first; }
    [InlineArray(289)] struct ElementChunk289 { private T _first; }
    [InlineArray(291)] struct ElementChunk291 { private T _first; }
    [InlineArray(292)] struct ElementChunk292 { private T _first; }
    [InlineArray(293)] struct ElementChunk293 { private T _first; }
    [InlineArray(295)] struct ElementChunk295 { private T _first; }
    [InlineArray(296)] struct ElementChunk296 { private T _first; }
    [InlineArray(297)] struct ElementChunk297 { private T _first; }
    [InlineArray(299)] struct ElementChunk299 { private T _first; }
    [InlineArray(300)] struct ElementChunk300 { private T _first; }
    [InlineArray(302)] struct ElementChunk302 { private T _first; }
    [InlineArray(303)] struct ElementChunk303 { private T _first; }
    [InlineArray(304)] struct ElementChunk304 { private T _first; }
    [InlineArray(306)] struct ElementChunk306 { private T _first; }
    [InlineArray(307)] struct ElementChunk307 { private T _first; }
    [InlineArray(309)] struct ElementChunk309 { private T _first; }
    [InlineArray(310)] struct ElementChunk310 { private T _first; }
    [InlineArray(312)] struct ElementChunk312 { private T _first; }
    [InlineArray(313)] struct ElementChunk313 { private T _first; }
    [InlineArray(315)] struct ElementChunk315 { private T _first; }
    [InlineArray(316)] struct ElementChunk316 { private T _first; }
    [InlineArray(318)] struct ElementChunk318 { private T _first; }
    [InlineArray(319)] struct ElementChunk319 { private T _first; }
    [InlineArray(321)] struct ElementChunk321 { private T _first; }
    [InlineArray(322)] struct ElementChunk322 { private T _first; }
    [InlineArray(324)] struct ElementChunk324 { private T _first; }
    [InlineArray(326)] struct ElementChunk326 { private T _first; }
    [InlineArray(327)] struct ElementChunk327 { private T _first; }
    [InlineArray(329)] struct ElementChunk329 { private T _first; }
    [InlineArray(330)] struct ElementChunk330 { private T _first; }
    [InlineArray(332)] struct ElementChunk332 { private T _first; }
    [InlineArray(334)] struct ElementChunk334 { private T _first; }
    [InlineArray(336)] struct ElementChunk336 { private T _first; }
    [InlineArray(337)] struct ElementChunk337 { private T _first; }
    [InlineArray(339)] struct ElementChunk339 { private T _first; }
    [InlineArray(341)] struct ElementChunk341 { private T _first; }
    [InlineArray(343)] struct ElementChunk343 { private T _first; }
    [InlineArray(344)] struct ElementChunk344 { private T _first; }
    [InlineArray(346)] struct ElementChunk346 { private T _first; }
    [InlineArray(348)] struct ElementChunk348 { private T _first; }
    [InlineArray(350)] struct ElementChunk350 { private T _first; }
    [InlineArray(352)] struct ElementChunk352 { private T _first; }
    [InlineArray(354)] struct ElementChunk354 { private T _first; }
    [InlineArray(356)] struct ElementChunk356 { private T _first; }
    [InlineArray(358)] struct ElementChunk358 { private T _first; }
    [InlineArray(360)] struct ElementChunk360 { private T _first; }
    [InlineArray(362)] struct ElementChunk362 { private T _first; }
    [InlineArray(364)] struct ElementChunk364 { private T _first; }
    [InlineArray(366)] struct ElementChunk366 { private T _first; }
    [InlineArray(368)] struct ElementChunk368 { private T _first; }
    [InlineArray(370)] struct ElementChunk370 { private T _first; }
    [InlineArray(372)] struct ElementChunk372 { private T _first; }
    [InlineArray(374)] struct ElementChunk374 { private T _first; }
    [InlineArray(376)] struct ElementChunk376 { private T _first; }
    [InlineArray(378)] struct ElementChunk378 { private T _first; }
    [InlineArray(381)] struct ElementChunk381 { private T _first; }
    [InlineArray(383)] struct ElementChunk383 { private T _first; }
    [InlineArray(385)] struct ElementChunk385 { private T _first; }
    [InlineArray(387)] struct ElementChunk387 { private T _first; }
    [InlineArray(390)] struct ElementChunk390 { private T _first; }
    [InlineArray(392)] struct ElementChunk392 { private T _first; }
    [InlineArray(394)] struct ElementChunk394 { private T _first; }
    [InlineArray(397)] struct ElementChunk397 { private T _first; }
    [InlineArray(399)] struct ElementChunk399 { private T _first; }
    [InlineArray(402)] struct ElementChunk402 { private T _first; }
    [InlineArray(404)] struct ElementChunk404 { private T _first; }
    [InlineArray(407)] struct ElementChunk407 { private T _first; }
    [InlineArray(409)] struct ElementChunk409 { private T _first; }
    [InlineArray(412)] struct ElementChunk412 { private T _first; }
    [InlineArray(414)] struct ElementChunk414 { private T _first; }
    [InlineArray(417)] struct ElementChunk417 { private T _first; }
    [InlineArray(420)] struct ElementChunk420 { private T _first; }
    [InlineArray(422)] struct ElementChunk422 { private T _first; }
    [InlineArray(425)] struct ElementChunk425 { private T _first; }
    [InlineArray(428)] struct ElementChunk428 { private T _first; }
    [InlineArray(431)] struct ElementChunk431 { private T _first; }
    [InlineArray(434)] struct ElementChunk434 { private T _first; }
    [InlineArray(436)] struct ElementChunk436 { private T _first; }
    [InlineArray(439)] struct ElementChunk439 { private T _first; }
    [InlineArray(442)] struct ElementChunk442 { private T _first; }
    [InlineArray(445)] struct ElementChunk445 { private T _first; }
    [InlineArray(448)] struct ElementChunk448 { private T _first; }
    [InlineArray(451)] struct ElementChunk451 { private T _first; }
    [InlineArray(455)] struct ElementChunk455 { private T _first; }
    [InlineArray(458)] struct ElementChunk458 { private T _first; }
    [InlineArray(461)] struct ElementChunk461 { private T _first; }
    [InlineArray(464)] struct ElementChunk464 { private T _first; }
    [InlineArray(468)] struct ElementChunk468 { private T _first; }
    [InlineArray(471)] struct ElementChunk471 { private T _first; }
    [InlineArray(474)] struct ElementChunk474 { private T _first; }
    [InlineArray(478)] struct ElementChunk478 { private T _first; }
    [InlineArray(481)] struct ElementChunk481 { private T _first; }
    [InlineArray(485)] struct ElementChunk485 { private T _first; }
    [InlineArray(489)] struct ElementChunk489 { private T _first; }
    [InlineArray(492)] struct ElementChunk492 { private T _first; }
    [InlineArray(496)] struct ElementChunk496 { private T _first; }
    [InlineArray(500)] struct ElementChunk500 { private T _first; }
    [InlineArray(504)] struct ElementChunk504 { private T _first; }
    [InlineArray(508)] struct ElementChunk508 { private T _first; }
    [InlineArray(511)] struct ElementChunk511 { private T _first; }
    [InlineArray(516)] struct ElementChunk516 { private T _first; }
    [InlineArray(520)] struct ElementChunk520 { private T _first; }
    [InlineArray(524)] struct ElementChunk524 { private T _first; }
    [InlineArray(528)] struct ElementChunk528 { private T _first; }
    [InlineArray(532)] struct ElementChunk532 { private T _first; }
    [InlineArray(537)] struct ElementChunk537 { private T _first; }
    [InlineArray(541)] struct ElementChunk541 { private T _first; }
    [InlineArray(546)] struct ElementChunk546 { private T _first; }
    [InlineArray(550)] struct ElementChunk550 { private T _first; }
    [InlineArray(555)] struct ElementChunk555 { private T _first; }
    [InlineArray(560)] struct ElementChunk560 { private T _first; }
    [InlineArray(564)] struct ElementChunk564 { private T _first; }
    [InlineArray(569)] struct ElementChunk569 { private T _first; }
    [InlineArray(574)] struct ElementChunk574 { private T _first; }
    [InlineArray(579)] struct ElementChunk579 { private T _first; }
    [InlineArray(585)] struct ElementChunk585 { private T _first; }
    [InlineArray(590)] struct ElementChunk590 { private T _first; }
    [InlineArray(595)] struct ElementChunk595 { private T _first; }
    [InlineArray(601)] struct ElementChunk601 { private T _first; }
    [InlineArray(606)] struct ElementChunk606 { private T _first; }
    [InlineArray(612)] struct ElementChunk612 { private T _first; }
    [InlineArray(618)] struct ElementChunk618 { private T _first; }
    [InlineArray(624)] struct ElementChunk624 { private T _first; }
    [InlineArray(630)] struct ElementChunk630 { private T _first; }
    [InlineArray(636)] struct ElementChunk636 { private T _first; }
    [InlineArray(642)] struct ElementChunk642 { private T _first; }
    [InlineArray(648)] struct ElementChunk648 { private T _first; }
    [InlineArray(655)] struct ElementChunk655 { private T _first; }
    [InlineArray(661)] struct ElementChunk661 { private T _first; }
    [InlineArray(668)] struct ElementChunk668 { private T _first; }
    [InlineArray(675)] struct ElementChunk675 { private T _first; }
    [InlineArray(682)] struct ElementChunk682 { private T _first; }
    [InlineArray(689)] struct ElementChunk689 { private T _first; }
    [InlineArray(697)] struct ElementChunk697 { private T _first; }
    [InlineArray(704)] struct ElementChunk704 { private T _first; }
    [InlineArray(712)] struct ElementChunk712 { private T _first; }
    [InlineArray(720)] struct ElementChunk720 { private T _first; }
    [InlineArray(728)] struct ElementChunk728 { private T _first; }
    [InlineArray(736)] struct ElementChunk736 { private T _first; }
    [InlineArray(744)] struct ElementChunk744 { private T _first; }
    [InlineArray(753)] struct ElementChunk753 { private T _first; }
    [InlineArray(762)] struct ElementChunk762 { private T _first; }
    [InlineArray(771)] struct ElementChunk771 { private T _first; }
    [InlineArray(780)] struct ElementChunk780 { private T _first; }
    [InlineArray(789)] struct ElementChunk789 { private T _first; }
    [InlineArray(799)] struct ElementChunk799 { private T _first; }
    [InlineArray(809)] struct ElementChunk809 { private T _first; }
    [InlineArray(819)] struct ElementChunk819 { private T _first; }
    [InlineArray(829)] struct ElementChunk829 { private T _first; }
    [InlineArray(840)] struct ElementChunk840 { private T _first; }
    [InlineArray(851)] struct ElementChunk851 { private T _first; }
    [InlineArray(862)] struct ElementChunk862 { private T _first; }
    [InlineArray(873)] struct ElementChunk873 { private T _first; }
    [InlineArray(885)] struct ElementChunk885 { private T _first; }
    [InlineArray(897)] struct ElementChunk897 { private T _first; }
    [InlineArray(910)] struct ElementChunk910 { private T _first; }
    [InlineArray(923)] struct ElementChunk923 { private T _first; }
    [InlineArray(936)] struct ElementChunk936 { private T _first; }
    [InlineArray(949)] struct ElementChunk949 { private T _first; }
    [InlineArray(963)] struct ElementChunk963 { private T _first; }
    [InlineArray(978)] struct ElementChunk978 { private T _first; }
    [InlineArray(992)] struct ElementChunk992 { private T _first; }
    [InlineArray(1008)] struct ElementChunk1008 { private T _first; }
    [InlineArray(1023)] struct ElementChunk1023 { private T _first; }
    [InlineArray(1040)] struct ElementChunk1040 { private T _first; }
    [InlineArray(1057)] struct ElementChunk1057 { private T _first; }
    [InlineArray(1074)] struct ElementChunk1074 { private T _first; }
    [InlineArray(1092)] struct ElementChunk1092 { private T _first; }
    [InlineArray(1110)] struct ElementChunk1110 { private T _first; }
    [InlineArray(1129)] struct ElementChunk1129 { private T _first; }
    [InlineArray(1149)] struct ElementChunk1149 { private T _first; }
    [InlineArray(1170)] struct ElementChunk1170 { private T _first; }
    [InlineArray(1191)] struct ElementChunk1191 { private T _first; }
    [InlineArray(1213)] struct ElementChunk1213 { private T _first; }
    [InlineArray(1236)] struct ElementChunk1236 { private T _first; }
    [InlineArray(1260)] struct ElementChunk1260 { private T _first; }
    [InlineArray(1285)] struct ElementChunk1285 { private T _first; }
    [InlineArray(1310)] struct ElementChunk1310 { private T _first; }
    [InlineArray(1337)] struct ElementChunk1337 { private T _first; }
    [InlineArray(1365)] struct ElementChunk1365 { private T _first; }
    [InlineArray(1394)] struct ElementChunk1394 { private T _first; }
    [InlineArray(1424)] struct ElementChunk1424 { private T _first; }
    [InlineArray(1456)] struct ElementChunk1456 { private T _first; }
    [InlineArray(1489)] struct ElementChunk1489 { private T _first; }
    [InlineArray(1524)] struct ElementChunk1524 { private T _first; }
    [InlineArray(1560)] struct ElementChunk1560 { private T _first; }
    [InlineArray(1598)] struct ElementChunk1598 { private T _first; }
    [InlineArray(1638)] struct ElementChunk1638 { private T _first; }
    [InlineArray(1680)] struct ElementChunk1680 { private T _first; }
    [InlineArray(1724)] struct ElementChunk1724 { private T _first; }
    [InlineArray(1771)] struct ElementChunk1771 { private T _first; }
    [InlineArray(1820)] struct ElementChunk1820 { private T _first; }
    [InlineArray(1872)] struct ElementChunk1872 { private T _first; }
    [InlineArray(1927)] struct ElementChunk1927 { private T _first; }
    [InlineArray(1985)] struct ElementChunk1985 { private T _first; }
    [InlineArray(2047)] struct ElementChunk2047 { private T _first; }
    [InlineArray(2114)] struct ElementChunk2114 { private T _first; }
    [InlineArray(2184)] struct ElementChunk2184 { private T _first; }
    [InlineArray(2259)] struct ElementChunk2259 { private T _first; }
    [InlineArray(2340)] struct ElementChunk2340 { private T _first; }
    [InlineArray(2427)] struct ElementChunk2427 { private T _first; }
    [InlineArray(2520)] struct ElementChunk2520 { private T _first; }
    [InlineArray(2621)] struct ElementChunk2621 { private T _first; }
    [InlineArray(2730)] struct ElementChunk2730 { private T _first; }
    [InlineArray(2849)] struct ElementChunk2849 { private T _first; }
    [InlineArray(2978)] struct ElementChunk2978 { private T _first; }
    [InlineArray(3120)] struct ElementChunk3120 { private T _first; }
    [InlineArray(3276)] struct ElementChunk3276 { private T _first; }
    [InlineArray(3449)] struct ElementChunk3449 { private T _first; }
    [InlineArray(3640)] struct ElementChunk3640 { private T _first; }
    [InlineArray(3855)] struct ElementChunk3855 { private T _first; }
    [InlineArray(4095)] struct ElementChunk4095 { private T _first; }
    [InlineArray(4369)] struct ElementChunk4369 { private T _first; }
    [InlineArray(4681)] struct ElementChunk4681 { private T _first; }
    [InlineArray(5041)] struct ElementChunk5041 { private T _first; }
    [InlineArray(5461)] struct ElementChunk5461 { private T _first; }
    [InlineArray(5957)] struct ElementChunk5957 { private T _first; }
    [InlineArray(6553)] struct ElementChunk6553 { private T _first; }
    [InlineArray(7281)] struct ElementChunk7281 { private T _first; }
    [InlineArray(8191)] struct ElementChunk8191 { private T _first; }
    [InlineArray(9362)] struct ElementChunk9362 { private T _first; }
    [InlineArray(10922)] struct ElementChunk10922 { private T _first; }
    [InlineArray(13107)] struct ElementChunk13107 { private T _first; }
    [InlineArray(16383)] struct ElementChunk16383 { private T _first; }
    [InlineArray(21845)] struct ElementChunk21845 { private T _first; }
    [InlineArray(32767)] struct ElementChunk32767 { private T _first; }
    [InlineArray(65535)] struct ElementChunk65535 { private T _first; }
}
